# Homework 1

### Exercise 1: Perceptron Mistakes

In [1]:
import numpy as np

### a)

In [3]:
# Training points 
x_1 = [-1,-1]
x_2 = [1,0]
x_3 = [-1,1.5]

# Labels
y_1 = 1
y_2 = -1
y_3 = 1

In [4]:
# Setting everything as a vector
x = np.array([x_1,x_2,x_3]).T

y = np.array([[y_1],[y_2],[y_3]])

In [5]:
## Starting with x_1:

n = max(x.shape)
n_errors = 0
th = np.array([[0,0]])
# th = x[:,0].reshape(1,2)
th_vec = th
i = 0
n_errors_overall = 0

while(1):

    n_errors = 0
    
    for i in range(n):         
        if y[i]*(np.dot(th,x[:,i])) <= 0:
            th = th + y[i]*x[:,i]
            print(th[0],end=",")
            n_errors += 1
            th_vec = np.append(th_vec,th,axis = 0)
        n_errors_overall += n_errors
        
    if(n_errors == 0):
        break
    
th_vec = th_vec[1:,:]
    

print('\n>> #Errors: {} \n'.format(len(th_vec)))       
print(">> Theta vectors:")
print(th_vec)

[-1. -1.],[-2.   0.5],
>> #Errors: 2 

>> Theta vectors:
[[-1.  -1. ]
 [-2.   0.5]]


In [6]:
## Starting with x_2:

n = max(x.shape)
n_errors = 0
th = np.array([[0,0]])
# th = x[:,0].reshape(1,2)
th_vec = th
i = 0
n_errors_overall = 0

while(1):
    
    i = 1
    n_errors = 0
    
    for i in range(n):   
        i = 1
        if y[i]*(np.dot(th,x[:,i])) <= 0:
            th = th + y[i]*x[:,i]
            print(th,end=",")
            n_errors += 1
            th_vec = np.append(th_vec,th,axis = 0)
        n_errors_overall += n_errors
        
    if(n_errors == 0):
        break
    
th_vec = th_vec[1:,:]
    

print('\n>> #Errors: {} \n'.format(len(th_vec)))       
print(">> Theta vectors:")
print(th_vec)

[[-1.  0.]],
>> #Errors: 1 

>> Theta vectors:
[[-1.  0.]]


### b) 

In [7]:
# Training points 
x_1 = [-1,-1]
x_2 = [1,0]
x_3 = [-1,10]

# Labels
y_1 = 1
y_2 = -1
y_3 = 1

In [8]:
## Starting with x_1:

n = max(x.shape)
n_errors = 0
th = np.array([[0,0]])
# th = x[:,0].reshape(1,2)
th_vec = th
i = 0
n_errors_overall = 0

while(1):

    n_errors = 0
    
    for i in range(n):         
        if y[i]*(np.dot(th,x[:,i])) <= 0:
            th = th + y[i]*x[:,i]
            print(th[0],end=",")
            n_errors += 1
            th_vec = np.append(th_vec,th,axis = 0)
        n_errors_overall += n_errors
        
    if(n_errors == 0):
        break
    
th_vec = th_vec[1:,:]
    

print('\n>> #Errors: {} \n'.format(len(th_vec)))       
print(">> Theta vectors:")s
print(th_vec)

[-1. -1.],[-2.   0.5],
>> #Errors: 2 

>> Theta vectors:
[[-1.  -1. ]
 [-2.   0.5]]


In [12]:
# Starting with x_2:

n = max(x.shape)
n_errors = 0
th = np.array([[0,0]])
# th = x[:,0].reshape(1,2)
th_vec = th
i = 0
n_errors_overall = 0

while(1):
    
    i = 1
    n_errors = 0
    
    for i in range(n):   
        i = 1
        if y[i]*(np.dot(th,x[:,i])) <= 0:
            th = th + y[i]*x[:,i]
            print(th,end=",")
            n_errors += 1
            th_vec = np.append(th_vec,th,axis = 0)
        n_errors_overall += n_errors
        
    if(n_errors == 0):
        break
    
th_vec = th_vec[1:,:]
    

print('\n>> #Errors: {} \n'.format(len(th_vec)))       
print(">> Theta vectors:")
print(th_vec)

[[-1.  0.]],
>> #Errors: 1 

>> Theta vectors:
[[-1.  0.]]
