# Homework 1

### Exercise 2: Perceptron Performance

In [1]:
import numpy as np

---
#### 2a)

In [2]:
# Training points 
x_1 = [-4,2]
x_2 = [-2,1]
x_3 = [-1,-1]
x_4 = [2,2]
x_5 = [1,-2]

# Labels
y_1 = 1
y_2 = 1
y_3 = -1
y_4 = -1
y_5 = -1

In [3]:
# Setting everything as a vector
x = np.array([x_1,x_2,x_3,x_4,x_5]).T

y = np.array([[y_1],[y_2],[y_3],[y_4],[y_5]])

In [4]:
## Starting with x_1:

n = max(x.shape)
n_errors = 0
th = np.array([[0,0]])
th_0 = 0
th_vec = th
n_errors = [0,0,0,0,0]

while(1):

    for i in range(n):         
        if y[i]*(np.dot(th,x[:,i])+th_0) <= 0:
            th = th + y[i]*x[:,i]
            th_0 = th_0 + y[i]
            print(th,th_0)
            n_errors[i] = n_errors[i] + 1
            th_vec = np.append(th_vec,th,axis = 0)
        
    if(n_errors[0] == 1 and n_errors[1] == 0 and n_errors[2] == 2 and n_errors[3] == 1 ):
        break
    
th_vec = th_vec[1:,:]
    

print('\n>> #Errors: {} \n'.format(len(th_vec)))       
print(">> Theta vectors:")
print(th_vec)

[[-4  2]] [1]
[[-3  3]] [0]
[[-5  1]] [-1]
[[-4  2]] [-2]

>> #Errors: 4 

>> Theta vectors:
[[-4  2]
 [-3  3]
 [-5  1]
 [-4  2]]


---
#### 2b)

In [5]:
# Training points 
x_1 = [-4,2]
x_2 = [-2,1]
x_3 = [-1,-1]
x_4 = [2,2]
x_5 = [1,-2]

# Labels
y_1 = 1
y_2 = 1
y_3 = -1
y_4 = -1
y_5 = -1

# Setting everything as a vector
x = np.array([x_1,x_2,x_3,x_4,x_5]).T

y = np.array([[y_1],[y_2],[y_3],[y_4],[y_5]])
                                       
                                       

In [17]:
n = max(x.shape)
n_errors = 0
th = np.array([[-3,3]])
th_0 = -3
n_error_overall = 0

while(1):

    n_errors = 0
    
    for i in range(n):         
        if y[i]*(np.dot(th,x[:,i])+th_0) <= 0:
            th = th + y[i]*x[:,i]
            th_0 = th_0 + y[i]
            n_errors += 1
            
    n_error_overall += n_errors 
    
    if(n_errors == 0):
        break
    

print('\n>> #Errors: {} \n'.format(n_error_overall))    
print(">> Theta vectors optimal:")
print(th)
print(">> Theta_0 vector optimal:")
print(th_0)


>> #Errors: 0 

>> Theta vectors optimal:
[[-3  3]]
>> Theta_0 vector optimal:
-3
