## Homework 1

### Exercirse 6: Perceptron updates

---
#### a) Number of updates (d = 2)

In [1]:
import numpy as np

In [2]:
# Training points 
x_1 = [np.cos(np.pi),0]
x_2 = [0,np.cos(2*np.pi)]


# Labels
y_1 = 1
y_2 = 1


# Setting everything as a vector
x = np.array([x_1,x_2]).T

y = np.array([[y_1],[y_2]])
                                       
                                       

In [3]:
## Perceptron algorithm

d = len(x)
n = d
th = np.array([0,0])
n_updates = 0


while(1):

    n_errors = 0
    
    for i in range(n):         
        if y[i]*(np.dot(th,x[:,i])) <= 0:
            th = th + y[i]*x[:,i]
            n_errors += 1
            
    n_updates += n_errors 
    
    if(n_errors == 0):
        break
    

print('\n>> # Updates: {} \n'.format(n_updates))    
print(">> Theta vectors optimal:")
print(th)


>> # Updates: 2 

>> Theta vectors optimal:
[-1.  1.]


---
#### b) Number of updates - General 
##### For simplicity, we'll take d = 3

In [4]:
# Training points 
x_1 = [np.cos(np.pi),0,0]
x_2 = [0,np.cos(2*np.pi),0]
x_3 = [0,0,np.cos(3*np.pi)]

# Labels
y_1 = 1
y_2 = 1
y_3 = -1


# Setting everything as a vector
x = np.array([x_1,x_2,x_3]).T

y = np.array([[y_1],[y_2],[y_3]])
                                       
                                       

In [5]:
## Perceptron algorithm

d = len(x)
n = d
th = np.array([0,0,0])
n_updates = 0

while(1):

    n_errors = 0
    
    for i in range(n):         
        if y[i]*(np.dot(th,x[:,i])) <= 0:
            th = th + y[i]*x[:,i]
            n_errors += 1
            print(th)
            
    n_updates += n_errors 
    
    if(n_errors == 0):
        break
    

print('\n>> # Updates: {} \n'.format(n_updates))    
print(">> Theta vectors optimal:")
print(th)

[-1.  0.  0.]
[-1.  1.  0.]
[-1.  1.  1.]

>> # Updates: 3 

>> Theta vectors optimal:
[-1.  1.  1.]


_From the two iterations in a) and b), we realize that the v = theta vector is composed of each of the non-zero components (1s) of the feature vectors x_i, and thus forms a vector that is perpendicular to the plane that contains all 3 of them._