# #1 NumPy Fundamentals


## Numpy Random

In [1]:
import numpy as np

In [2]:
def randomization(n):
    
    A = np.random.rand(n,1)
        
    return A
    
    raise NotImplementedError


In [3]:
print(randomization(5))

[[0.43786276]
 [0.43867656]
 [0.2045941 ]
 [0.51552451]
 [0.67719524]]


## Matrix Operation

In [4]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.rand(h,w) 
    B = np.random.rand(h,w) 
    
    s = A + B
    
    return [A,B,s]
        
    raise NotImplementedError

In [5]:
result1 = operations(3,3)

for mat in result1:
    print()
    print(mat)


[[0.44115183 0.04453506 0.54673612]
 [0.06671732 0.1340738  0.86685162]
 [0.93005364 0.1618357  0.19908862]]

[[0.3948403  0.27918846 0.12553942]
 [0.62621015 0.37826075 0.25256007]
 [0.46188274 0.78013176 0.20415417]]

[[0.83599213 0.32372352 0.67227554]
 [0.69292746 0.51233455 1.11941169]
 [1.39193638 0.94196746 0.4032428 ]]


In [6]:
result2 = operations(3,2)

for mat in result2:
    print()
    print(mat)


[[0.02839324 0.08071519]
 [0.20449012 0.50195747]
 [0.95817227 0.20519082]]

[[0.87264472 0.32246768]
 [0.24709092 0.57288504]
 [0.67170735 0.91018314]]

[[0.90103795 0.40318287]
 [0.45158104 1.07484251]
 [1.62987963 1.11537397]]


## Min, Max & Norm

In [7]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    
    return np.linalg.norm(A + B)
    
    raise NotImplementedError


In [8]:
norm(result1[0],result1[1])

2.4977482219375076

# #2 Neural Network with NumPy

In [9]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    
    return np.tanh(np.dot(np.transpose(weights), inputs))
    
    raise NotImplementedError

In [10]:
x = np.array([[5],[1]])
w = np.array([[4],[-3]])

print(neural_network(x,w))

[[1.]]


# #3 Vector function

## Scalar Function

In [11]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    
    return x*y if x<=y else x/y 
    
    
    raise NotImplementedError
    
    

In [12]:
# x < y 
print('Case x < y: ',scalar_function(4,28))

# x = y 
print('Case x > y: ',scalar_function(4,28))

# x > y 
print('Case x > y: ',scalar_function(28,4))



Case x < y:  112
Case x > y:  112
Case x > y:  7.0



## Vector Function

In [13]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    
    vect_func =  np.vectorize(scalar_function)

    return vect_func(x,y)
    
    raise NotImplementedError


In [14]:
# x < y 
print('Case x < y: ',vector_function([4,5],[7,12]))

# x = y 
print('Case x > y: ',vector_function([4,5],[7,12]))

# x > y 
print('Case x > y: ',vector_function([28,36],[7,4]))


Case x < y:  [28 60]
Case x > y:  [28 60]
Case x > y:  [4. 9.]



### _*For more fundamentals, check the other two files in this folder (Numpy, vector, broadcasting, matplotlib)_

## Python Debbuging wit pdb

In [19]:
import pdb
pdb.set_trace()

## Input 'exit' or 'quit' to exit 

--Call--
> d:\programfiles\anaconda3\lib\site-packages\ipython\core\displayhook.py(252)__call__()
-> def __call__(self, result=None):
(Pdb) ex
*** NameError: name 'ex' is not defined
(Pdb) exi
*** NameError: name 'exi' is not defined
(Pdb) exit


BdbQuit: 

In [20]:
## Equivalently:
breakpoint()

--Call--
> d:\programfiles\anaconda3\lib\site-packages\ipython\core\displayhook.py(252)__call__()
-> def __call__(self, result=None):
(Pdb) exit


BdbQuit: 